substitutions:
  _SERVICE_NAME: python-web-app                      # Chosen service name
  _REGION: us-west1                                  # Confirmed region
  _AR_REPO: gke-repo                                 # Artifact Registry repo name
  
steps:
# 1. Build the Docker Image
# CRITICAL FIX: The final argument is now './Microservices', which explicitly tells
# the Docker builder to use this folder as the build context.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    - 'build'
    - '-t'
    - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}'
    - './Microservices' # <--- EXPLICIT PATH: Solves the 'no such file or directory' error

# 2. Push the built image to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    - 'push'
    - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}'

# 3. Deploy the new image revision to Cloud Run
- name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
  id: Deploy
  args:
    - gcloud
    - run
    - deploy
    - ${_SERVICE_NAME}
    - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}
    - --region=${_REGION}
    - --platform=managed
    - --allow-unauthenticated
    - --project=${PROJECT_ID}
  waitFor: ['Push']
  
images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}'
options:
  logging: CLOUD_LOGGING_ONLY