substitutions:
  _SERVICE_NAME: python-web-app
  _REGION: us-west1
  _AR_REPO: gke-repo

steps:
# 1. Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    - 'build'
    - '-t'
    - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}'
    - '--file=Dockerfile'
    - '.'  # 👈 use current directory as context

# 2. Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    - 'push'
    - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}'

# 3. Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  id: Deploy
  args:
    - gcloud
    - run
    - deploy
    - ${_SERVICE_NAME}
    - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}
    - --region=${_REGION}
    - --platform=managed
    - --allow-unauthenticated
    - --project=${PROJECT_ID}
  waitFor: ['Push']

images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
